#!/usr/bin/env python3
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = SRC / "app.bundle.js"

ORDER = [
    SRC / "linalg.js",
    SRC / "quaternion.js",
    SRC / "control.js",
    SRC / "quadcopter.js",
    SRC / "renderer.js",
    SRC / "app.js",
]


IMPORT_RE = re.compile(r'import\s*\{([^}]*)\}\s*from\s*"[^"]+";\s*', re.MULTILINE | re.DOTALL)


def transform_module(text: str) -> str:
    exports: list[str] = []
    text = IMPORT_RE.sub(_replace_import, text)

    def replace_function(match: re.Match) -> str:
        name = match.group(1)
        exports.append(name)
        return f"function {name}("

    def replace_class(match: re.Match) -> str:
        name = match.group(1)
        exports.append(name)
        return f"class {name} "

    def replace_const(match: re.Match) -> str:
        name = match.group(1)
        exports.append(name)
        return f"const {name} ="

    text = re.sub(r'export\s+function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(', replace_function, text)
    text = re.sub(r'export\s+class\s+([A-Za-z_][A-Za-z0-9_]*)\s*', replace_class, text)
    text = re.sub(r'export\s+const\s+([A-Za-z_][A-Za-z0-9_]*)\s*=', replace_const, text)

    export_lines = "".join(f"window.__ACL__.{name} = {name};\n" for name in exports)
    return text.strip() + "\n\n" + export_lines


def _replace_import(match: re.Match) -> str:
    names = ", ".join(part.strip() for part in match.group(1).replace("\n", " ").split(",") if part.strip())
    return f"const {{ {names} }} = window.__ACL__;\n"


def main() -> None:
    chunks = [
        "// Generated by scripts/build_bundle.py\n",
        "window.__ACL__ = window.__ACL__ || {};\n\n",
    ]

    for path in ORDER:
        chunks.append(f"// ----- {path.name} -----\n")
        chunks.append("{\n")
        chunks.append(transform_module(path.read_text()))
        chunks.append("}\n")
        chunks.append("\n")

    OUT.write_text("".join(chunks))
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
