#!/usr/bin/env python3
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = SRC / "app.bundle.js"

ORDER = [
    SRC / "linalg.js",
    SRC / "quaternion.js",
    SRC / "control.js",
    SRC / "quadcopter.js",
    SRC / "renderer.js",
    SRC / "app.js",
]


IMPORT_RE = re.compile(r'import\s*\{([^}]*)\}\s*from\s*"[^"]+";\s*', re.MULTILINE | re.DOTALL)


def transform_module(text: str) -> str:
    text = IMPORT_RE.sub(_replace_import, text)
    text = re.sub(
        r'export\s+function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(',
        lambda match: f'window.__ACL__.{match.group(1)} = function {match.group(1)}(',
        text,
    )
    text = re.sub(
        r'export\s+class\s+([A-Za-z_][A-Za-z0-9_]*)\s*',
        lambda match: f'window.__ACL__.{match.group(1)} = class {match.group(1)} ',
        text,
    )
    text = re.sub(
        r'export\s+const\s+([A-Za-z_][A-Za-z0-9_]*)\s*=',
        lambda match: f'window.__ACL__.{match.group(1)} =',
        text,
    )
    return text.strip() + "\n"


def _replace_import(match: re.Match) -> str:
    names = ", ".join(part.strip() for part in match.group(1).replace("\n", " ").split(",") if part.strip())
    return f"const {{ {names} }} = window.__ACL__;\n"


def main() -> None:
    chunks = [
        "// Generated by scripts/build_bundle.py\n",
        "window.__ACL__ = window.__ACL__ || {};\n\n",
    ]

    for path in ORDER:
        chunks.append(f"// ----- {path.name} -----\n")
        chunks.append(transform_module(path.read_text()))
        chunks.append("\n")

    OUT.write_text("".join(chunks))
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
